OrdererOrgs:
  - Name: Orderer
    Domain: filecont.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Org1
    Domain: org1.filecont.com
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Org2
    Domain: org2.filecont.com
    Template:
      Count: 1
    Users:
      Count: 1 