Profiles:

    FourOrgOrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Org1
                    - *Org2
                    - *Org3
                    - *Org4
    OneOrgChannel:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Org1
                - *Org2                      
    TwoOrgChannel:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Org3
                - *Org4

Organizations:

    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/trch.com/msp

    - &Org1
        Name: Org1MSP
        ID: Org1MSP
        MSPDir: crypto-config/peerOrganizations/org1.trch.com/msp
        AnchorPeers:
            - Host: peer0.org1.trch.com
              Port: 7051

    - &Org2
        Name: Org2MSP
        ID: Org2MSP
        MSPDir: crypto-config/peerOrganizations/org2.trch.com/msp
        AnchorPeers:
            - Host: peer0.org2.trch.com
              Port: 7051

    - &Org3
        Name: Org3MSP
        ID: Org3MSP
        MSPDir: crypto-config/peerOrganizations/org3.trch.com/msp
        AnchorPeers:
            - Host: peer0.org3.trch.com
              Port: 7051
    
    - &Org4
        Name: Org4MSP
        ID: Org4MSP
        MSPDir: crypto-config/peerOrganizations/org4.trch.com/msp
        AnchorPeers:
            - Host: peer0.org4.trch.com
              Port: 7051
              

Orderer: &OrdererDefaults

    OrdererType: solo

    Addresses:
        - orderer.trch.com:7050

    BatchTimeout: 2s

    BatchSize:
        MaxMessageCount: 10      
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Kafka:
        Brokers:
            - 127.0.0.1:9092

    Organizations:


Application: &ApplicationDefaults

    Organizations:
