OrdererOrgs:
  - Name: Orderer
    Domain: trch.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Org1
    Domain: org1.trch.com
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Org2
    Domain: org2.trch.com
    Template:
      Count: 1
    Users:
      Count: 1 
  - Name: Org3
    Domain: org3.trch.com
    Template:
      Count: 1
    Users:
      Count: 1 
  - Name: Org4
    Domain: org4.trch.com
    Template:
      Count: 1
    Users:
      Count: 1     