OrdererOrgs:
  - Name: Orderer
    Domain: trnc.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Org1
    Domain: org1.trnc.com
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Org2
    Domain: org2.trnc.com
    Template:
      Count: 1 
    Users:
      Count: 1 
 