OrdererOrgs:
  - Name: Orderer
    Domain: dsch.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Org1
    Domain: org1.dsch.com
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Org2
    Domain: org2.dsch.com
    Template:
      Count: 2
    Users:
      Count: 1 
  - Name: Org3
    Domain: org3.dsch.com
    Template:
      Count: 2
    Users:
      Count: 1 